site_name: Bow Simulator
site_description: Bow Simulator is a free software tool for Windows and Linux that allows you to create virtual bow models and simulate their performance.
site_author: Stefan Pfeifer
repo_url: 'https://gitlab.com/bow-simulator'

# theme_dir: themes/cinder

theme: cinder

pages:
    - Home: index.md
    - News: news.md
    - Download: download.md
    - Resources: resources.md
    - About:
        - Mailing Lists: mailing-lists.md
        - Getting Involved: contributing.md
        - Contact: contact.md
