site_name: Bow Simulator - Bow and Arrow Physics Simulation
site_favicon: images/logo.ico
site_author: Stefan Pfeifer
theme_dir: themes/cinder
repo_url: 'https://gitlab.com/bow-simulator'
pages:
    - Home: index.md
    - News: news.md
    - Download: download.md
    - Resources: resources.md
    - About:
        - Mailing Lists: mailing-lists.md
        - Getting Involved: contributing.md
        - Contact: contact.md
