site_name: VirtualBow
site_description: Software tool for designing and simulating bows
site_author: Stefan Pfeifer

repo_url: "https://github.com/bow-simulation/virtualbow/"
edit_uri: ""

theme: cinder

nav:
    - Home: index.md
    - News: news.md
    - Download: download.md
    - Resources: resources.md
    - About:
        - Discussion: discussion.md
        - Getting Involved: contributing.md
        - Contact: contact.md
