site_name: VirtualBow
site_description: Software tool for designing and simulating bows
site_author: Stefan Pfeifer

repo_url: "https://github.com/bow-simulation/virtualbow/"
edit_uri: ""

extra_css:
    - extra.css

theme:
    name: mkdocs
    nav_style: light
    custom_dir: custom_theme

nav:
    - Home: index.md
    - News: news.md
    - Download: download.md
    - Resources: resources.md
    - About: about.md
