site_name: VirtualBow
site_url: https://www.virtualbow.org/
site_description: Software tool for designing and simulating bows
site_author: Stefan Pfeifer

repo_url: "https://github.com/bow-simulation/virtualbow/"
edit_uri: ""

extra_css:
    - extra.css

theme:
    name: null
    custom_dir: cinder/

nav:
    - Home: index.md
    - News: news.md
    - Download: download.md
    - Documentation:
        - User Manual: ../files/user-manual/
        - Theory Manual: ../files/theory-manual.pdf
        - Resources: resources.md
    - About:
        - Contact & Support: contact.md
        - Getting Involved: contributing.md
        - Donate: https://www.paypal.com/donate/?hosted_button_id=CZUXPF6ZCSEZU